// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "page": {
        "license": "© <date></date> <eclair>ÉCLAIR</eclair>. Tous droits réservés.",
        "madeByECLAIR": "Développé par ÉCLAIR"
    }
};
export default messages;