// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HelloAssoButton": {
    "payWithHA": "Payer avec <ha>HelloAsso</ha>"
  },
  "MyECLButton": {
    "authenticate": "Se connecter avec MyECL"
  },
  "datePicker": {
    "select": "Sélectionner une date"
  },
  "multiselect": {
    "deselect": "Tout désélectionner",
    "noItemFound": "Aucun objet trouvé.",
    "search": "Recherche...",
    "selectAll": "Tout sélectionner"
  },
  "pageIndicator": {
    "nextPage": "Aller à la page suivante",
    "previousPage": "Aller à la page précédente"
  },
  "statusDialog": {
    "continue": "Continuer"
  },
  "toast": {
    "error": "Erreur"
  },
  "warningDialog": {
    "cancel": "Annuler"
  }
};
export default messages;